### ISSUE TITLE
"Sorry, the requested file does not exist on this server."

### ISSUE THREAD

**Issue by Deftl** [H2CK/hm_kostalpiko#1]
Hallo Thorsten, 

Erst einmal absolut Klasse dieses AddOn zum Auslesen eines Kostal Piko mit der Homematic bereitzustellen!

Gemäß deiner sehr guten Anleitung habe ich folgende Schritte erfolgreich absolvieren können:
- download von github
- Installation über das WebUI meiner CCU2
- Konfiguration der Parameter 
   - IP Adresse
   - username
   - passwort
   - variablenpräfix

Leider sehe ich im Logfile immer folgende Fehlermeldung:
"Sorry, the requested file does not exist on this server."

Hast du hier einen Tipp bzw. Lösung für mich?

Grüße 

Christian

**Comment by Deftl** [comment]
Es handelt sich beim Wechselrichter um einen PIKO 10 mit der Firmware 05.07

**Comment by H2CK** [comment]
Die Fehlermeldung scheint der Wechselrichter zu senden. D.h. die im AddOn hinterlegte URL zum Herunterladen der Informationen ist mit deinem Wechselrichter nicht kompatibel.
Ich habe dies mit einem KOSTAL PIKO 4.6 mit den Versionen UI 06.41 und FW 05.61 getestet. Dort funktioniert dies ohne Probleme. Kannst du ein Update der Software-Version für deinen KOSTAL Wechselrichter machen? Welche UI Version hast du (diese ist relevant)?

**Comment by Deftl** [comment]
Aktuell habe ich folgende Versionen auf meinem PIKO 10:
> FW 05.07
> HW 0100
> UI 05.12
> PAR 02.08

Ich versuche mal hochzuziehen was geht und melde mich dann nochmal...

**Comment by Deftl** [comment]
Finde im Downloadbereich von Kostal keine Updatemöglichkeiten. Muss mich erst mal an den Support wenden wie es scheint...

**Comment by Deftl** [comment]
Super,

Das update auf UI 06.41 brachte den Erfolg.

Sehe die Daten jetzt im Logfile! Klasse 😆
